name: Pull Request Stats
on:
  push:
      branches:
          - develop
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          organization: 'teamq-ecuador'
          period: 14
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'
